---
kind: pipeline
name: linux_aarch64_python3.7

platform:
  os: linux
  arch: arm64
  dist: bionic

steps:
- name: Install and build
  image: arm64v8/python:3.7
  environment:
    CONFIG: linux_aarch64_python3.7
    PLATFORM: linux-aarch64
    TESTMODE: full
    COVERAGE:
  commands:
    - python -c 'import sys; print("Python debug build:", hasattr(sys, "gettotalrefcount"))'
    - apt-get install wget libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev swig libmpc-dev
    - wget -q "https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh"  -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda3
    - export PATH=$HOME/miniconda3/bin:$PATH
    - conda config --set always_yes yes --set auto_update_conda false
    - conda install pip conda
    - conda update -n base conda 
    - conda info -a  
    - conda install pytest scipy mpmath Cython pybind11 coverage
    - python -c 'import numpy as np; print("relaxed strides checking:", np.ones((10,1),order="C").flags.f_contiguous)'
    # Make sure that relaxed strides checking is actually in effect; otherwise fail loudly
    - if [ "$NPY_RELAXED_STRIDES_CHECKING" == "1" ]; then python -c'import numpy as np; assert np.ones((10,1),order="C").flags.f_contiguous'; fi
    # Test that mpmath actually uses gmpy2
    - python -u runtests.py -g -m $TESTMODE $COVERAGE $USE_WHEEL_BUILD -- -rfEX | tee runtests.log
    - tools/validate_runtests_log.py $TESTMODE < runtests.log
    - if [ "${REFGUIDE_CHECK}" == "1" ]; then python runtests.py -g --refguide-check; fi
    - if [ "${ASV_CHECK}" == "1" ]; then (cd benchmarks && python -masv check -E existing); fi
    # Check dynamic symbol hiding works on Linux
    - ./tools/check_pyext_symbol_hiding.sh build
